name: tests

on:
  pull_request_target:

permissions:
  id-token: write
  contents: read

jobs:
  empty-matrix:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get array
        id: get_array
        uses: ./.github/actions/return-empty-array
        
      - name: Run Matrix
        uses: ./.github/actions/run-matrix
        with:
          values: ${{ fromJSON(steps.get_array.outputs.value) }}


  dependabot-auto-approve:
    needs: [empty-matrix]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      # if: github.actor == 'dependabot[bot]'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
